"""Office Deployment Tool configuration: reproduce an installation, don't invent one.

The generator is a pure function over what was detected, so the XML can be
reviewed and tested without an Office install anywhere near it. It reproduces
the product ids, bitness, language and update channel that were found; it does
not choose them, and it never contains a product key.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path
from xml.dom import minidom

from .scan.office import OfficeInstallation
from .util import process

#: ODT expects "32"/"64", the registry records "x86"/"x64".
EDITION_BY_PLATFORM = {"x86": "32", "x64": "64"}

SETUP_TIMEOUT_SECONDS = 3600


def generate_configuration(installation: OfficeInstallation, *, display_level: str = "Full") -> str:
    """Build an ODT ``configuration.xml`` matching a detected installation."""
    if not installation.present:
        raise ValueError("no Office installation was detected to reproduce")

    configuration = ET.Element("Configuration")
    add = ET.SubElement(configuration, "Add")
    edition = EDITION_BY_PLATFORM.get(installation.platform.lower())
    if edition:
        add.set("OfficeClientEdition", edition)
    if installation.channel:
        add.set("Channel", installation.channel)

    language = installation.client_culture or "MatchInstalled"
    for product_id in installation.product_ids:
        product = ET.SubElement(add, "Product", {"ID": product_id})
        ET.SubElement(product, "Language", {"ID": language})

    ET.SubElement(configuration, "Display", {"Level": display_level, "AcceptEULA": "TRUE"})
    ET.SubElement(configuration, "Property", {"Name": "AUTOACTIVATE", "Value": "0"})
    configuration.append(
        ET.Comment(
            " Generated by WinMigrate to reproduce the Office installation found on "
            "the source machine. It contains no product key: activation is completed "
            "by the user, by signing in or by entering a key they own. "
        )
    )
    raw = ET.tostring(configuration, encoding="unicode")
    return minidom.parseString(raw).toprettyxml(indent="  ")


def run_setup(setup_executable: Path, configuration_path: Path, runner=process.run):
    """Invoke ``setup.exe /configure <configuration.xml>``.

    The Office Deployment Tool is a separate download; this only runs a copy the
    user already has, and never fetches one.
    """
    return runner(
        [str(setup_executable), "/configure", str(configuration_path)],
        timeout=SETUP_TIMEOUT_SECONDS,
    )
